/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminHorsesRouteImport } from './routes/admin/horses'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReleaseVersionsRouteImport } from './routes/admin/release-versions'
import { Route as AdminShiftPatternsRouteImport } from './routes/admin/shift-patterns'
import { Route as AdminSpacesRouteImport } from './routes/admin/spaces'
import { Route as AdminTasksRouteImport } from './routes/admin/tasks'
import { Route as AdminThresholdsRouteImport } from './routes/admin/thresholds'
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers'
import { Route as AdminWhiteboardReadRouteImport } from './routes/admin/whiteboard-read'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as HorsesIndexRouteImport } from './routes/horses/index'
import { Route as HorsesHorseIdRouteImport } from './routes/horses/$horseId'
import { Route as ShiftsShiftIdRouteImport } from './routes/shifts.$shiftId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHorsesRoute = AdminHorsesRouteImport.update({
  id: '/admin/horses',
  path: '/admin/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReleaseVersionsRoute = AdminReleaseVersionsRouteImport.update({
  id: '/admin/release-versions',
  path: '/admin/release-versions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShiftPatternsRoute = AdminShiftPatternsRouteImport.update({
  id: '/admin/shift-patterns',
  path: '/admin/shift-patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpacesRoute = AdminSpacesRouteImport.update({
  id: '/admin/spaces',
  path: '/admin/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThresholdsRoute = AdminThresholdsRouteImport.update({
  id: '/admin/thresholds',
  path: '/admin/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/admin/volunteers',
  path: '/admin/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhiteboardReadRoute = AdminWhiteboardReadRouteImport.update({
  id: '/admin/whiteboard-read',
  path: '/admin/whiteboard-read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesIndexRoute = HorsesIndexRouteImport.update({
  id: '/horses/',
  path: '/horses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesHorseIdRoute = HorsesHorseIdRouteImport.update({
  id: '/horses/$horseId',
  path: '/horses/$horseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsShiftIdRoute = ShiftsShiftIdRouteImport.update({
  id: '/$shiftId',
  path: '/$shiftId',
  getParentRoute: () => ShiftsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/board': typeof BoardRoute
  '/contacts': typeof ContactsRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/shifts': typeof ShiftsRouteWithChildren
  '/supplies': typeof SuppliesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/shift-patterns': typeof AdminShiftPatternsRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/thresholds': typeof AdminThresholdsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/whiteboard-read': typeof AdminWhiteboardReadRoute
  '/api/$': typeof ApiSplatRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/shifts/$shiftId': typeof ShiftsShiftIdRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/board': typeof BoardRoute
  '/contacts': typeof ContactsRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/shifts': typeof ShiftsRouteWithChildren
  '/supplies': typeof SuppliesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/shift-patterns': typeof AdminShiftPatternsRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/thresholds': typeof AdminThresholdsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/whiteboard-read': typeof AdminWhiteboardReadRoute
  '/api/$': typeof ApiSplatRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/shifts/$shiftId': typeof ShiftsShiftIdRoute
  '/horses': typeof HorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/board': typeof BoardRoute
  '/contacts': typeof ContactsRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/shifts': typeof ShiftsRouteWithChildren
  '/supplies': typeof SuppliesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/shift-patterns': typeof AdminShiftPatternsRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/thresholds': typeof AdminThresholdsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/whiteboard-read': typeof AdminWhiteboardReadRoute
  '/api/$': typeof ApiSplatRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/shifts/$shiftId': typeof ShiftsShiftIdRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/board'
    | '/contacts'
    | '/escalations'
    | '/login'
    | '/shifts'
    | '/supplies'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/contacts'
    | '/admin/horses'
    | '/admin/products'
    | '/admin/release-versions'
    | '/admin/shift-patterns'
    | '/admin/spaces'
    | '/admin/tasks'
    | '/admin/thresholds'
    | '/admin/volunteers'
    | '/admin/whiteboard-read'
    | '/api/$'
    | '/horses/$horseId'
    | '/shifts/$shiftId'
    | '/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/board'
    | '/contacts'
    | '/escalations'
    | '/login'
    | '/shifts'
    | '/supplies'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/contacts'
    | '/admin/horses'
    | '/admin/products'
    | '/admin/release-versions'
    | '/admin/shift-patterns'
    | '/admin/spaces'
    | '/admin/tasks'
    | '/admin/thresholds'
    | '/admin/volunteers'
    | '/admin/whiteboard-read'
    | '/api/$'
    | '/horses/$horseId'
    | '/shifts/$shiftId'
    | '/horses'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/board'
    | '/contacts'
    | '/escalations'
    | '/login'
    | '/shifts'
    | '/supplies'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/contacts'
    | '/admin/horses'
    | '/admin/products'
    | '/admin/release-versions'
    | '/admin/shift-patterns'
    | '/admin/spaces'
    | '/admin/tasks'
    | '/admin/thresholds'
    | '/admin/volunteers'
    | '/admin/whiteboard-read'
    | '/api/$'
    | '/horses/$horseId'
    | '/shifts/$shiftId'
    | '/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  BoardRoute: typeof BoardRoute
  ContactsRoute: typeof ContactsRoute
  EscalationsRoute: typeof EscalationsRoute
  LoginRoute: typeof LoginRoute
  ShiftsRoute: typeof ShiftsRouteWithChildren
  SuppliesRoute: typeof SuppliesRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminHorsesRoute: typeof AdminHorsesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReleaseVersionsRoute: typeof AdminReleaseVersionsRoute
  AdminShiftPatternsRoute: typeof AdminShiftPatternsRoute
  AdminSpacesRoute: typeof AdminSpacesRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminThresholdsRoute: typeof AdminThresholdsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminWhiteboardReadRoute: typeof AdminWhiteboardReadRoute
  ApiSplatRoute: typeof ApiSplatRoute
  HorsesHorseIdRoute: typeof HorsesHorseIdRoute
  HorsesIndexRoute: typeof HorsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/horses': {
      id: '/admin/horses'
      path: '/admin/horses'
      fullPath: '/admin/horses'
      preLoaderRoute: typeof AdminHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/release-versions': {
      id: '/admin/release-versions'
      path: '/admin/release-versions'
      fullPath: '/admin/release-versions'
      preLoaderRoute: typeof AdminReleaseVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shift-patterns': {
      id: '/admin/shift-patterns'
      path: '/admin/shift-patterns'
      fullPath: '/admin/shift-patterns'
      preLoaderRoute: typeof AdminShiftPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spaces': {
      id: '/admin/spaces'
      path: '/admin/spaces'
      fullPath: '/admin/spaces'
      preLoaderRoute: typeof AdminSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/thresholds': {
      id: '/admin/thresholds'
      path: '/admin/thresholds'
      fullPath: '/admin/thresholds'
      preLoaderRoute: typeof AdminThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/admin/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whiteboard-read': {
      id: '/admin/whiteboard-read'
      path: '/admin/whiteboard-read'
      fullPath: '/admin/whiteboard-read'
      preLoaderRoute: typeof AdminWhiteboardReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/': {
      id: '/horses/'
      path: '/horses'
      fullPath: '/horses/'
      preLoaderRoute: typeof HorsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/$horseId': {
      id: '/horses/$horseId'
      path: '/horses/$horseId'
      fullPath: '/horses/$horseId'
      preLoaderRoute: typeof HorsesHorseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/$shiftId': {
      id: '/shifts/$shiftId'
      path: '/$shiftId'
      fullPath: '/shifts/$shiftId'
      preLoaderRoute: typeof ShiftsShiftIdRouteImport
      parentRoute: typeof ShiftsRoute
    }
  }
}

interface ShiftsRouteChildren {
  ShiftsShiftIdRoute: typeof ShiftsShiftIdRoute
}

const ShiftsRouteChildren: ShiftsRouteChildren = {
  ShiftsShiftIdRoute: ShiftsShiftIdRoute,
}

const ShiftsRouteWithChildren =
  ShiftsRoute._addFileChildren(ShiftsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  BoardRoute: BoardRoute,
  ContactsRoute: ContactsRoute,
  EscalationsRoute: EscalationsRoute,
  LoginRoute: LoginRoute,
  ShiftsRoute: ShiftsRouteWithChildren,
  SuppliesRoute: SuppliesRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminHorsesRoute: AdminHorsesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReleaseVersionsRoute: AdminReleaseVersionsRoute,
  AdminShiftPatternsRoute: AdminShiftPatternsRoute,
  AdminSpacesRoute: AdminSpacesRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminThresholdsRoute: AdminThresholdsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminWhiteboardReadRoute: AdminWhiteboardReadRoute,
  ApiSplatRoute: ApiSplatRoute,
  HorsesHorseIdRoute: HorsesHorseIdRoute,
  HorsesIndexRoute: HorsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
