/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminReleaseVersionsRouteImport } from './routes/admin/release-versions'
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReleaseVersionsRoute = AdminReleaseVersionsRouteImport.update({
  id: '/admin/release-versions',
  path: '/admin/release-versions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/admin/volunteers',
  path: '/admin/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/release-versions'
    | '/admin/volunteers'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/release-versions'
    | '/admin/volunteers'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/audit'
    | '/admin/release-versions'
    | '/admin/volunteers'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminReleaseVersionsRoute: typeof AdminReleaseVersionsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/release-versions': {
      id: '/admin/release-versions'
      path: '/admin/release-versions'
      fullPath: '/admin/release-versions'
      preLoaderRoute: typeof AdminReleaseVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/admin/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminReleaseVersionsRoute: AdminReleaseVersionsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
