/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminHorsesRouteImport } from './routes/admin/horses'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReleaseVersionsRouteImport } from './routes/admin/release-versions'
import { Route as AdminSpacesRouteImport } from './routes/admin/spaces'
import { Route as AdminThresholdsRouteImport } from './routes/admin/thresholds'
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as HorsesIndexRouteImport } from './routes/horses/index'
import { Route as HorsesHorseIdRouteImport } from './routes/horses/$horseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHorsesRoute = AdminHorsesRouteImport.update({
  id: '/admin/horses',
  path: '/admin/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReleaseVersionsRoute = AdminReleaseVersionsRouteImport.update({
  id: '/admin/release-versions',
  path: '/admin/release-versions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpacesRoute = AdminSpacesRouteImport.update({
  id: '/admin/spaces',
  path: '/admin/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThresholdsRoute = AdminThresholdsRouteImport.update({
  id: '/admin/thresholds',
  path: '/admin/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/admin/volunteers',
  path: '/admin/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesIndexRoute = HorsesIndexRouteImport.update({
  id: '/horses/',
  path: '/horses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesHorseIdRoute = HorsesHorseIdRouteImport.update({
  id: '/horses/$horseId',
  path: '/horses/$horseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/thresholds': typeof AdminThresholdsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/api/$': typeof ApiSplatRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/thresholds': typeof AdminThresholdsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/api/$': typeof ApiSplatRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses': typeof HorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/release-versions': typeof AdminReleaseVersionsRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/thresholds': typeof AdminThresholdsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/api/$': typeof ApiSplatRoute
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/login'
    | '/admin/audit'
    | '/admin/horses'
    | '/admin/products'
    | '/admin/release-versions'
    | '/admin/spaces'
    | '/admin/thresholds'
    | '/admin/volunteers'
    | '/api/$'
    | '/horses/$horseId'
    | '/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/login'
    | '/admin/audit'
    | '/admin/horses'
    | '/admin/products'
    | '/admin/release-versions'
    | '/admin/spaces'
    | '/admin/thresholds'
    | '/admin/volunteers'
    | '/api/$'
    | '/horses/$horseId'
    | '/horses'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/login'
    | '/admin/audit'
    | '/admin/horses'
    | '/admin/products'
    | '/admin/release-versions'
    | '/admin/spaces'
    | '/admin/thresholds'
    | '/admin/volunteers'
    | '/api/$'
    | '/horses/$horseId'
    | '/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  LoginRoute: typeof LoginRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminHorsesRoute: typeof AdminHorsesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReleaseVersionsRoute: typeof AdminReleaseVersionsRoute
  AdminSpacesRoute: typeof AdminSpacesRoute
  AdminThresholdsRoute: typeof AdminThresholdsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  ApiSplatRoute: typeof ApiSplatRoute
  HorsesHorseIdRoute: typeof HorsesHorseIdRoute
  HorsesIndexRoute: typeof HorsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/horses': {
      id: '/admin/horses'
      path: '/admin/horses'
      fullPath: '/admin/horses'
      preLoaderRoute: typeof AdminHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/release-versions': {
      id: '/admin/release-versions'
      path: '/admin/release-versions'
      fullPath: '/admin/release-versions'
      preLoaderRoute: typeof AdminReleaseVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/spaces': {
      id: '/admin/spaces'
      path: '/admin/spaces'
      fullPath: '/admin/spaces'
      preLoaderRoute: typeof AdminSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/thresholds': {
      id: '/admin/thresholds'
      path: '/admin/thresholds'
      fullPath: '/admin/thresholds'
      preLoaderRoute: typeof AdminThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/admin/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/': {
      id: '/horses/'
      path: '/horses'
      fullPath: '/horses/'
      preLoaderRoute: typeof HorsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/$horseId': {
      id: '/horses/$horseId'
      path: '/horses/$horseId'
      fullPath: '/horses/$horseId'
      preLoaderRoute: typeof HorsesHorseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  LoginRoute: LoginRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminHorsesRoute: AdminHorsesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReleaseVersionsRoute: AdminReleaseVersionsRoute,
  AdminSpacesRoute: AdminSpacesRoute,
  AdminThresholdsRoute: AdminThresholdsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  ApiSplatRoute: ApiSplatRoute,
  HorsesHorseIdRoute: HorsesHorseIdRoute,
  HorsesIndexRoute: HorsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
